description: The personal site of Simon Weber.
canonical: www.simonmweber.com
markdown: kramdown
future: true
gems:
    - jekyll-sitemap
exclude:
    - Makefile
    - README.md
    - Gemfile
    - Gemfile.lock
    - .gitignore
